### ISSUE TITLE
Category access is not respected

### ISSUE THREAD

**Issue by Erftralle** [JoomGalleryfriends/JoomFinderPlugin#4]
When changing the category access it is not respected by the smart search. Images in a category with limited access are still listed in a smart search.

**Comment by Elfangor93** [comment]
Issue should be fixed with the commit ce541a8

**Comment by Erftralle** [comment]
There is still a problem left. Think of a category structure like this (access of all categories public):

= Members
= = Elfangor
= = = ElfangorCopy

If I change the access of the category "Elfangor" to "Registered" images of "ElfangorCopy" are still listed in a public smart search. Clicking on an image link throws the error "500 Unable to load image with ID X".
Using the standard search (either gallery or plugin) does not list them. 

By the way. You should follow the signature of "onJoomSearch" according to https://github.com/JoomGalleryfriends/JoomAdditionalImageFields/blob/bd9ea31fdf85a19a56b8d7ef084d2699cf16b40c/joomadditionalimagefields.php#L301 means making the third parameter a parameter with default value. So it does not conflict e.g. with the standard search using plugin.

**Comment by Elfangor93** [comment]
Fixwd with commit 8035811

**Comment by Erftralle** [comment]
There is still a problem left.

When changing the access in the category manager the smart search reacts now as expected.
But after clearing the index in the Smart Search and then indexing again the category access is still not respected.

> By the way. You should follow the signature of "onJoomSearch" according to https://github.com/JoomGalleryfriends/JoomAdditionalImageFields/blob/bd9ea31fdf85a19a56b8d7ef084d2699cf16b40c/joomadditionalimagefields.php#L301 means making the third parameter a parameter with default value. So it does not conflict e.g. with the standard search using plugin.

Also not fixed yet.

**Comment by Elfangor93** [comment]
> By the way. You should follow the signature of "onJoomSearch" according to https://github.com/JoomGalleryfriends/JoomAdditionalImageFields/blob/bd9ea31fdf85a19a56b8d7ef084d2699cf16b40c/joomadditionalimagefields.php#L301 means making the third parameter a parameter with default value. So it does not conflict e.g. with the standard search using plugin.

Oke, did it with commit 0477a8c

**Comment by Elfangor93** [comment]
> But after clearing the index in the Smart Search and then indexing again the category access is still not respected.

This case is tricky. I have to think about a solution for that...

**Comment by Elfangor93** [comment]
>But after clearing the index in the Smart Search and then indexing again the category access is still not respected.

Fixed with commit db913fd
